spring:
    application:
        name: Books Storage
    data:
          mongodb.host: localhost
          mongodb.port: 27017
          mongodb.uri: mongodb://localhost/data
          mongo.repositories.enabled: true
    activemq:
          pool:
            enabled: false
          broker-url: vm://localhost
          user: admin
          password: admin

server:
  port: 8096

logging:
  file: logs/book-storage.log

management:
  context-path: /-system
  port: 8097
  security:
    enabled: false

endpoints:
  health:
    sensitive: false
  info:
    sensitive: false

httpClients:
  booksService:
    auth:
      enabled: true
      credentials:
        login: admin
        password: admin1

penguin-books:
  endpoint:
   resources: https://reststop.randomhouse.com/resources
   ping: https://reststop.randomhouse.com

ip-geolocation:
  endpoint: https://api.ipgeolocation.io

location:
  result-page: https://localhost:8093/books/results